=== AcalaNetwork/jamtestvectors/pvm/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "initial-regs": {
      "type": "array",
      "items": {
        "type": "integer",
        "minimum": 0,
        "maximum": 4294967295
      },
      "minItems": 13,
      "maxItems": 13
    },
    "initial-pc": {
      "type": "integer",
      "minimum": 0,
      "maximum": 4294967295
    },
    "code": {
      "type": "array",
      "items": {
        "type": "integer",
        "minimum": 0,
        "maximum": 255
      }
    },
    "expected-status": {
      "type": "string",
      "enum": ["trap", "halt"]
    },
    "expected-regs": {
      "type": "array",
      "items": {
        "type": "integer",
        "minimum": 0,
        "maximum": 4294967295
      },
      "minItems": 13,
      "maxItems": 13
    },
    "expected-pc": {
      "type": "integer",
      "minimum": 0,
      "maximum": 4294967295
    }
  },
  "required": ["name", "initial-regs", "code", "expected-status", "expected-regs"],
  "additionalProperties": false
}

=== AcalaNetwork/jamtestvectors/pvm/programs/inst_shift_arithmetic_right_imm.json
{
  "name": "inst_shift_arithmetic_right_imm",
  "initial-regs": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    2147483765,
    0,
    0,
    0,
    0,
    0
  ],
  "initial-pc": 0,
  "code": [
    0,
    0,
    3,
    25,
    121,
    3,
    249
  ],
  "expected-status": "trap",
  "expected-regs": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    2147483765,
    0,
    4026531854,
    0,
    0,
    0
  ],
  "expected-pc": 3
}

=== AcalaNetwork/jamtestvectors/pvm/programs/inst_xor.json
{
  "name": "inst_xor",
  "initial-regs": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    5,
    3,
    0,
    0,
    0,
    0
  ],
  "code": [
    0,
    0,
    3,
    28,
    121,
    8,
    249
  ],
  "expected-status": "trap",
  "expected-regs": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    5,
    3,
    6,
    0,
    0,
    0
  ]
}
